name: Manual Workflow Trigger

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Target environment'
        required: true
        default: 'staging'
        type: choice
        options:
          - 'staging'
          - 'production'

      message:
        description: 'Custom message for the run'
        required: false
        type: string

jobs:
  my_job:
    runs-on: ubuntu-latest
    steps:
      - name: Print inputs
        run: |
          echo "Running in environment: ${{ github.event.inputs.environment }}"
          echo "Message: ${{ github.event.inputs.message }}"
