name: Manual Workflow Trigger

on:
  workflow_dispatch:
    inputs:
      enviroment:
        description: 'Target enviroment'
        required: ture
        default: 'staging'
        type: choice
        options:
          - 'Staging'
          - 'production'
        message:
          description: 'Custom message for the run'
          required: false
          type: string

jobs:
  my_jobs:
    runs-on: ubuntu-latest
    steps:
      - name: Print inputs
      run: |
        echo "Running in enviroment: $ {{ github.event.inputs.enviroments }}"
        echo "Message : $ {{ github.event.inputs.message }}"