name: Run Python Script

on: push  # Runs when you push code

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Get your code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'  # Change to your version

      # Step 3: Run the script
      - name: Run main.py
        run: python main.py
